/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ChecklistItem = IDL.Record({
  'id' : IDL.Text,
  'description' : IDL.Text,
  'itemType' : IDL.Text,
});
export const ChecklistTemplate = IDL.Record({
  'id' : IDL.Text,
  'items' : IDL.Vec(ChecklistItem),
  'machineType' : IDL.Text,
});
export const Machine = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'department' : IDL.Text,
  'location' : IDL.Text,
  'machineType' : IDL.Text,
});
export const PMPlan = IDL.Record({
  'month' : IDL.Nat,
  'checklistTemplateId' : IDL.Text,
  'frequency' : IDL.Text,
  'machineId' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Order = IDL.Variant({
  'less' : IDL.Null,
  'equal' : IDL.Null,
  'greater' : IDL.Null,
});
export const ChecklistResult = IDL.Record({
  'photoFilename' : IDL.Text,
  'remark' : IDL.Text,
  'itemId' : IDL.Text,
  'value' : IDL.Text,
});
export const PMRecord = IDL.Record({
  'id' : IDL.Text,
  'completedDate' : IDL.Int,
  'status' : IDL.Text,
  'operatorName' : IDL.Text,
  'operatorId' : IDL.Text,
  'machineId' : IDL.Text,
  'checklistResults' : IDL.Vec(ChecklistResult),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addChecklistTemplate' : IDL.Func([ChecklistTemplate], [], []),
  'addMachine' : IDL.Func([Machine], [], []),
  'addPMPlan' : IDL.Func([PMPlan], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'compareText' : IDL.Func([IDL.Text, IDL.Text], [Order], ['query']),
  'deleteMachine' : IDL.Func([IDL.Text], [], []),
  'getAllMachines' : IDL.Func([], [IDL.Vec(Machine)], ['query']),
  'getAllPMRecords' : IDL.Func([], [IDL.Vec(PMRecord)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChecklistTemplate' : IDL.Func([IDL.Text], [ChecklistTemplate], ['query']),
  'getTodaysPlan' : IDL.Func([IDL.Nat], [IDL.Vec(PMPlan)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitPMRecord' : IDL.Func([PMRecord], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ChecklistItem = IDL.Record({
    'id' : IDL.Text,
    'description' : IDL.Text,
    'itemType' : IDL.Text,
  });
  const ChecklistTemplate = IDL.Record({
    'id' : IDL.Text,
    'items' : IDL.Vec(ChecklistItem),
    'machineType' : IDL.Text,
  });
  const Machine = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'department' : IDL.Text,
    'location' : IDL.Text,
    'machineType' : IDL.Text,
  });
  const PMPlan = IDL.Record({
    'month' : IDL.Nat,
    'checklistTemplateId' : IDL.Text,
    'frequency' : IDL.Text,
    'machineId' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Order = IDL.Variant({
    'less' : IDL.Null,
    'equal' : IDL.Null,
    'greater' : IDL.Null,
  });
  const ChecklistResult = IDL.Record({
    'photoFilename' : IDL.Text,
    'remark' : IDL.Text,
    'itemId' : IDL.Text,
    'value' : IDL.Text,
  });
  const PMRecord = IDL.Record({
    'id' : IDL.Text,
    'completedDate' : IDL.Int,
    'status' : IDL.Text,
    'operatorName' : IDL.Text,
    'operatorId' : IDL.Text,
    'machineId' : IDL.Text,
    'checklistResults' : IDL.Vec(ChecklistResult),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addChecklistTemplate' : IDL.Func([ChecklistTemplate], [], []),
    'addMachine' : IDL.Func([Machine], [], []),
    'addPMPlan' : IDL.Func([PMPlan], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'compareText' : IDL.Func([IDL.Text, IDL.Text], [Order], ['query']),
    'deleteMachine' : IDL.Func([IDL.Text], [], []),
    'getAllMachines' : IDL.Func([], [IDL.Vec(Machine)], ['query']),
    'getAllPMRecords' : IDL.Func([], [IDL.Vec(PMRecord)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChecklistTemplate' : IDL.Func(
        [IDL.Text],
        [ChecklistTemplate],
        ['query'],
      ),
    'getTodaysPlan' : IDL.Func([IDL.Nat], [IDL.Vec(PMPlan)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitPMRecord' : IDL.Func([PMRecord], [], []),
  });
};

export const init = ({ IDL }) => { return []; };