/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ChecklistItem {
  'id' : string,
  'description' : string,
  'itemType' : string,
}
export interface ChecklistResult {
  'photoFilename' : string,
  'remark' : string,
  'itemId' : string,
  'value' : string,
}
export interface ChecklistTemplate {
  'id' : string,
  'items' : Array<ChecklistItem>,
  'machineType' : string,
}
export interface Machine {
  'id' : string,
  'name' : string,
  'department' : string,
  'location' : string,
  'machineType' : string,
}
export type Order = { 'less' : null } |
  { 'equal' : null } |
  { 'greater' : null };
export interface PMPlan {
  'month' : bigint,
  'checklistTemplateId' : string,
  'frequency' : string,
  'machineId' : string,
}
export interface PMRecord {
  'id' : string,
  'completedDate' : bigint,
  'status' : string,
  'operatorName' : string,
  'operatorId' : string,
  'machineId' : string,
  'checklistResults' : Array<ChecklistResult>,
}
export interface UserProfile { 'name' : string, 'role' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addChecklistTemplate' : ActorMethod<[ChecklistTemplate], undefined>,
  'addMachine' : ActorMethod<[Machine], undefined>,
  'addPMPlan' : ActorMethod<[PMPlan], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'compareText' : ActorMethod<[string, string], Order>,
  'deleteMachine' : ActorMethod<[string], undefined>,
  'getAllMachines' : ActorMethod<[], Array<Machine>>,
  'getAllPMRecords' : ActorMethod<[], Array<PMRecord>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChecklistTemplate' : ActorMethod<[string], ChecklistTemplate>,
  'getTodaysPlan' : ActorMethod<[bigint], Array<PMPlan>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitPMRecord' : ActorMethod<[PMRecord], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];